@extends('layouts.admin')
@section('title', $product->exists ? 'Ubah produk' : 'Tambah produk')
@section('heading', $product->exists ? 'Ubah produk' : 'Tambah produk')
@section('content')
@if ($errors->any())<div class="mb-5 rounded-xl border border-jahe/30 bg-jahe/10 p-4 text-sm text-jahe"><ul class="list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="post" enctype="multipart/form-data" action="{{ $product->exists ? route('admin.products.update', $product) : route('admin.products.store') }}" class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_20rem]">@csrf @if($product->exists) @method('PUT') @endif
<div class="space-y-5 rounded-card border border-garis bg-white p-5 sm:p-6">
<h2 class="font-display text-xl font-bold text-arang">Informasi produk</h2>
<label class="block font-semibold text-arang">Nama produk<input name="name" required autofocus value="{{ old('name', $product->name) }}" class="mt-2 min-h-12 w-full rounded-xl border border-garis px-4 outline-none focus:border-daun"></label>
<label class="block font-semibold text-arang">Kategori<select name="category" required class="mt-2 min-h-12 w-full rounded-xl border border-garis bg-white px-4 outline-none focus:border-daun"><option value="">Pilih kategori</option>@foreach(\App\Models\Product::CATEGORIES as $value => $label)<option value="{{ $value }}" @selected(old('category', $product->category) === $value)>{{ $label }}</option>@endforeach</select></label>
<label class="block font-semibold text-arang">Ringkasan<textarea name="short_description" maxlength="255" rows="2" class="mt-2 w-full rounded-xl border border-garis p-4 outline-none focus:border-daun">{{ old('short_description', $product->short_description) }}</textarea></label>
<label class="block font-semibold text-arang">Deskripsi<textarea name="description" rows="7" class="mt-2 w-full rounded-xl border border-garis p-4 outline-none focus:border-daun">{{ old('description', $product->description) }}</textarea></label>
<div class="grid gap-4 sm:grid-cols-2"><label class="font-semibold text-arang">Harga (Rp)<input type="number" min="0" name="price" required value="{{ old('price', $product->price) }}" class="mt-2 min-h-12 w-full rounded-xl border border-garis px-4"></label><label class="font-semibold text-arang">Stok<input type="number" min="0" name="stock" required value="{{ old('stock', $product->stock ?? 0) }}" class="mt-2 min-h-12 w-full rounded-xl border border-garis px-4"></label><label class="font-semibold text-arang">Berat (gram)<input type="number" min="0" name="weight_grams" value="{{ old('weight_grams', $product->weight_grams) }}" class="mt-2 min-h-12 w-full rounded-xl border border-garis px-4"></label><label class="font-semibold text-arang">Asal produk<input name="origin" value="{{ old('origin', $product->origin) }}" class="mt-2 min-h-12 w-full rounded-xl border border-garis px-4"></label></div>
<label class="block font-semibold text-arang">Cara penyimpanan<textarea name="storage_instructions" rows="3" class="mt-2 w-full rounded-xl border border-garis p-4">{{ old('storage_instructions', $product->storage_instructions) }}</textarea></label>
</div>
<aside class="space-y-5 lg:sticky lg:top-20 lg:self-start"><div class="rounded-card border border-garis bg-white p-5"><p class="font-display text-lg font-bold text-arang">Gambar produk</p><p class="mt-1 text-xs leading-5 text-kabut">Gunakan foto tajam dengan latar bersih, idealnya persegi dan maksimum 4 MB.</p>@if($product->imageUrl())<img id="image-preview" src="{{ $product->imageUrl() }}" alt="Pratinjau produk" class="mt-3 aspect-square w-full rounded-xl object-cover">@else<img id="image-preview" alt="Pratinjau produk" class="mt-3 hidden aspect-square w-full rounded-xl object-cover">@endif<label class="mt-3 flex min-h-12 cursor-pointer items-center gap-2 rounded-xl border border-dashed border-garis px-3 text-sm font-semibold text-daun"><x-icon name="upload" /><span>Pilih gambar</span><input type="file" name="image" accept="image/*" class="sr-only" onchange="document.getElementById('image-preview').src=URL.createObjectURL(this.files[0]);document.getElementById('image-preview').classList.remove('hidden')"></label></div>
<div class="rounded-card border border-garis bg-white p-5"><label class="block font-semibold text-arang">Status<select name="status" class="mt-2 min-h-12 w-full rounded-xl border border-garis bg-white px-4"><option value="draft" @selected(old('status', $product->status ?? 'draft') === 'draft')>Draf</option><option value="published" @selected(old('status', $product->status) === 'published')>Terbit</option></select></label><label class="mt-5 flex min-h-12 items-center gap-3"><input type="checkbox" name="is_promoted" value="1" @checked(old('is_promoted', $product->is_promoted)) class="h-5 w-5 accent-daun"><span><strong class="block text-arang">Pilihan GoTerapis</strong><small class="text-kabut">Ditempatkan lebih dahulu dalam katalog, bukan sebagai banner.</small></span></label></div>
<div class="rounded-card border border-garis bg-white p-5"><button class="min-h-12 w-full rounded-full bg-daun px-5 font-semibold text-white hover:bg-daun-tua">{{ $product->exists ? 'Simpan perubahan' : 'Simpan produk' }}</button><a href="{{ route('admin.products.index') }}" class="mt-2 flex min-h-11 items-center justify-center font-semibold text-kabut">Batal</a></div></aside>
</form>
@endsection
