@extends('layouts.app')
@section('title', 'Toko Produk Terapi & Herbal')
@section('meta', 'Jelajahi produk herbal dan perlengkapan terapi yang tersedia di GoTerapis.')
@section('content')
<section class="border-b border-garis bg-kertas py-5 sm:py-8"><div class="mx-auto max-w-6xl px-4">
@if ($banners->isNotEmpty())
<div class="relative overflow-hidden rounded-card border border-garis bg-white" x-data="{ active: 0, total: {{ $banners->count() }}, next() { this.active = (this.active + 1) % this.total }, previous() { this.active = (this.active - 1 + this.total) % this.total } }" x-on:keydown.left.prevent="previous()" x-on:keydown.right.prevent="next()" tabindex="0" role="region" aria-roledescription="carousel" aria-label="Kampanye GoTerapis">
@foreach ($banners as $banner)
<article x-show="active === {{ $loop->index }}" @if(!$loop->first) style="display:none" @endif class="grid lg:grid-cols-[3fr_2fr]">
<div class="aspect-[12/5] overflow-hidden bg-daun-muda lg:aspect-auto lg:min-h-[28rem]"><img src="{{ $banner->imageUrl() }}" alt="" class="h-full w-full object-cover" @if($loop->first) fetchpriority="high" @else loading="lazy" @endif></div>
<div class="flex min-h-64 flex-col justify-center bg-daun-tua p-7 text-white sm:p-10 lg:p-12"><p class="text-xs font-bold uppercase tracking-[.2em] text-kunyit">Pilihan GoTerapis</p><h1 class="mt-4 font-display text-3xl font-bold leading-tight sm:text-4xl">{{ $banner->title }}</h1>@if($banner->subtitle)<p class="mt-4 leading-7 text-white/80">{{ $banner->subtitle }}</p>@endif @if($banner->cta_label)<a href="{{ $banner->cta_url }}" class="mt-7 inline-flex min-h-12 w-fit items-center gap-2 border-b-2 border-kunyit font-semibold text-white">{{ $banner->cta_label }} <x-icon name="arrow-right" /></a>@endif</div>
</article>
@endforeach
@if($banners->count() > 1)<div class="absolute bottom-4 right-4 flex items-center gap-2 bg-white p-2"><button type="button" x-on:click="previous()" class="grid h-10 w-10 place-items-center border border-garis text-arang" aria-label="Kampanye sebelumnya"><x-icon name="arrow-left" /></button><span class="min-w-12 text-center text-sm font-semibold text-kabut"><span x-text="active + 1"></span> / {{ $banners->count() }}</span><button type="button" x-on:click="next()" class="grid h-10 w-10 place-items-center border border-garis text-arang" aria-label="Kampanye berikutnya"><x-icon name="arrow-right" /></button></div>@endif
</div>
@else
<div class="grid overflow-hidden rounded-card border border-garis bg-daun-muda lg:grid-cols-[3fr_2fr]"><div class="flex min-h-80 flex-col justify-center p-8 sm:p-12"><p class="text-xs font-bold uppercase tracking-[.2em] text-daun">Toko GoTerapis</p><h1 class="mt-4 max-w-2xl font-display text-4xl font-bold leading-tight text-arang sm:text-5xl">Perawatan yang baik dimulai dari pilihan yang tepat.</h1><p class="mt-5 max-w-xl leading-7 text-kabut">Temukan herbal dan perlengkapan terapi untuk mendukung rutinitas perawatan dengan lebih tenang.</p><a href="#katalog-produk" class="mt-7 inline-flex min-h-12 w-fit items-center gap-2 border-b-2 border-daun font-semibold text-daun">Jelajahi katalog <x-icon name="arrow-right" /></a></div><div class="hidden bg-daun-tua lg:grid lg:place-items-center"><x-icon name="leaf" class="h-28 w-28 text-kunyit" /></div></div>
@endif
</div></section>
<section id="katalog-produk" class="mx-auto max-w-6xl scroll-mt-20 px-4 py-10 sm:py-14">
<div class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-[.18em] text-daun">Katalog</p><h2 class="mt-2 font-display text-3xl font-bold text-arang">Produk untuk perawatan</h2></div><p class="text-sm text-kabut">{{ $products->total() }} produk ditemukan</p></div>
<form method="get" class="mt-7 grid gap-3 border-y border-garis py-5 sm:grid-cols-[1fr_16rem_auto]"><label class="sr-only" for="q">Cari produk</label><input id="q" name="q" value="{{ request('q') }}" placeholder="Cari nama atau manfaat produk…" class="min-h-12 border border-garis bg-white px-4 outline-none focus:border-daun"><label class="sr-only" for="category">Kategori</label><select id="category" name="category" class="min-h-12 border border-garis bg-white px-4 outline-none focus:border-daun"><option value="">Semua kategori</option>@foreach(\App\Models\Product::CATEGORIES as $value => $label)<option value="{{ $value }}" @selected(request('category') === $value)>{{ $label }}</option>@endforeach</select><button class="min-h-12 bg-daun px-6 font-semibold text-white hover:bg-daun-tua">Terapkan</button></form>
<div class="mt-8 grid gap-x-5 gap-y-8 sm:grid-cols-2 lg:grid-cols-3">@forelse($products as $product)<a href="{{ route('products.show', $product) }}" class="group border-b border-garis bg-white pb-5"><div class="relative aspect-[4/3] overflow-hidden bg-daun-muda">@if($product->imageUrl())<img src="{{ $product->imageUrl() }}" alt="{{ $product->name }}" class="h-full w-full object-cover">@else<span class="grid h-full place-items-center text-daun"><x-icon name="leaf" class="h-14 w-14" /></span>@endif @if($product->is_promoted)<span class="absolute left-3 top-3 bg-kunyit px-3 py-1 text-xs font-semibold text-arang">Pilihan GoTerapis</span>@endif</div><div class="pt-4"><p class="text-xs font-bold uppercase tracking-wide text-daun">{{ $product->categoryLabel() }}</p><h3 class="mt-2 font-display text-xl font-bold text-arang group-hover:text-daun">{{ $product->name }}</h3>@if($product->short_description)<p class="mt-2 line-clamp-2 text-sm leading-6 text-kabut">{{ $product->short_description }}</p>@endif<div class="mt-4 flex justify-between gap-3"><p class="font-bold text-arang">Rp{{ number_format($product->price, 0, ',', '.') }}</p><p class="text-sm text-kabut">{{ $product->stock > 0 ? 'Stok '.$product->stock : 'Stok habis' }}</p></div></div></a>@empty<div class="rounded-card border border-garis bg-daun-muda p-10 text-center sm:col-span-2 lg:col-span-3"><h3 class="font-display text-xl font-bold text-arang">Produk belum ditemukan</h3><p class="mt-2 text-kabut">Coba kata kunci lain atau lihat semua kategori.</p><a href="{{ route('products.index') }}" class="mt-4 inline-flex border-b border-daun font-semibold text-daun">Lihat semua produk</a></div>@endforelse</div><div class="mt-8">{{ $products->links() }}</div>
</section>
@endsection
