@extends('layouts.admin')
@section('title', $banner->exists ? 'Ubah banner promosi' : 'Tambah banner promosi')
@section('heading', $banner->exists ? 'Ubah banner promosi' : 'Tambah banner promosi')
@section('content')
@if ($errors->any())<div class="mb-5 rounded-xl border border-jahe/30 bg-jahe/10 p-4 text-sm text-jahe"><ul class="list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="post" enctype="multipart/form-data" action="{{ $banner->exists ? route('admin.banners.update', $banner) : route('admin.banners.store') }}" class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_20rem]">@csrf @if($banner->exists) @method('PUT') @endif
<div class="space-y-6">
<section class="rounded-card border border-garis bg-white p-5 sm:p-6"><p class="text-xs font-bold uppercase tracking-[.16em] text-kabut">Artwork kampanye</p><h2 class="mt-2 font-display text-2xl font-bold text-arang">Visual utama toko</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-kabut">Gunakan gambar horizontal ideal 1920 × 800 piksel. Tempatkan subjek penting di area tengah agar tetap aman saat tampil di berbagai layar.</p>@if($banner->exists)<img id="image-preview" src="{{ $banner->imageUrl() }}" alt="Pratinjau banner" class="mt-5 aspect-[12/5] w-full rounded-xl object-cover">@else<img id="image-preview" alt="Pratinjau banner" class="mt-5 hidden aspect-[12/5] w-full rounded-xl object-cover">@endif<label class="mt-4 flex min-h-12 cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-garis text-sm font-semibold text-daun hover:border-daun"><x-icon name="upload" />Pilih artwork<input type="file" name="image" accept="image/*" @required(!$banner->exists) class="sr-only" onchange="document.getElementById('image-preview').src=URL.createObjectURL(this.files[0]);document.getElementById('image-preview').classList.remove('hidden')"></label><p class="mt-2 text-xs text-kabut">Minimum 1200 × 480 piksel, maksimum 6 MB. Sistem menyimpan WebP hingga lebar 1920 piksel.</p></section>
<section class="space-y-5 rounded-card border border-garis bg-white p-5 sm:p-6"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-kabut">Pesan kampanye</p><h2 class="mt-2 font-display text-xl font-bold text-arang">Naskah dan tindakan</h2></div><label class="block font-semibold text-arang">Judul<input name="title" required maxlength="120" autofocus value="{{ old('title', $banner->title) }}" class="mt-2 min-h-12 w-full rounded-xl border border-garis px-4 outline-none focus:border-daun"></label><label class="block font-semibold text-arang">Subjudul<textarea name="subtitle" maxlength="220" rows="3" class="mt-2 w-full rounded-xl border border-garis p-4 outline-none focus:border-daun">{{ old('subtitle', $banner->subtitle) }}</textarea></label><div class="grid gap-4 sm:grid-cols-2"><label class="font-semibold text-arang">Label CTA<input name="cta_label" maxlength="40" value="{{ old('cta_label', $banner->cta_label) }}" placeholder="Contoh: Lihat koleksi" class="mt-2 min-h-12 w-full rounded-xl border border-garis px-4"></label><label class="font-semibold text-arang">Tautan CTA<input name="cta_url" maxlength="2048" value="{{ old('cta_url', $banner->cta_url) }}" placeholder="/produk?category=..." class="mt-2 min-h-12 w-full rounded-xl border border-garis px-4"></label></div><p class="text-xs text-kabut">Isi label dan tautan bersamaan. Tautan harus berupa path internal yang diawali / atau URL HTTPS.</p></section>
</div>
<aside class="space-y-5 lg:sticky lg:top-20 lg:self-start"><section class="rounded-card border border-garis bg-white p-5"><p class="text-xs font-bold uppercase tracking-[.16em] text-kabut">Penayangan</p><label class="mt-4 flex items-start gap-3"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $banner->is_active)) class="mt-1 h-5 w-5 accent-daun"><span><strong class="block text-arang">Aktifkan banner</strong><small class="text-kabut">Tetap mengikuti jadwal mulai dan berakhir.</small></span></label><label class="mt-5 block font-semibold text-arang">Urutan<input type="number" name="sort_order" min="0" required value="{{ old('sort_order', $banner->sort_order ?? 0) }}" class="mt-2 min-h-12 w-full rounded-xl border border-garis px-4"></label><label class="mt-5 block font-semibold text-arang">Mulai tayang<input type="datetime-local" name="starts_at" value="{{ old('starts_at', $banner->starts_at?->format('Y-m-d\TH:i')) }}" class="mt-2 min-h-12 w-full rounded-xl border border-garis px-3"></label><label class="mt-5 block font-semibold text-arang">Berakhir<input type="datetime-local" name="ends_at" value="{{ old('ends_at', $banner->ends_at?->format('Y-m-d\TH:i')) }}" class="mt-2 min-h-12 w-full rounded-xl border border-garis px-3"></label></section><section class="rounded-card border border-garis bg-white p-5"><button class="min-h-12 w-full rounded-xl bg-daun px-5 font-semibold text-white hover:bg-daun-tua">{{ $banner->exists ? 'Simpan perubahan' : 'Simpan banner' }}</button><a href="{{ route('admin.banners.index') }}" class="mt-2 flex min-h-11 items-center justify-center font-semibold text-kabut">Batal</a></section></aside>
</form>
@endsection
