@extends('layouts.admin')
@section('title', 'Detail Pesanan Toko')
@section('heading', $order->code)
@section('subheading', 'Detail dan tindakan pesanan toko')
@section('content')
<div class="grid gap-5 lg:grid-cols-[1fr_360px]"><div class="space-y-5"><section class="rounded-card border border-garis bg-white p-5"><h2 class="font-display text-lg font-bold text-arang">Barang</h2><div class="mt-4 space-y-3">@foreach($order->items as $item)<div class="flex justify-between gap-4 text-sm"><span>{{ $item->product_name }} × {{ $item->quantity }}</span><strong>Rp{{ number_format($item->subtotal, 0, ',', '.') }}</strong></div>@endforeach<div class="flex justify-between border-t border-garis-muda pt-3 text-sm"><span>Subtotal</span><strong>Rp{{ number_format($order->subtotal, 0, ',', '.') }}</strong></div></div></section><section class="rounded-card border border-garis bg-white p-5"><h2 class="font-display text-lg font-bold text-arang">Alamat</h2><p class="mt-3 text-sm leading-6 text-kabut">{{ $order->recipient_name }} · {{ $order->phone }}<br>{{ $order->address }}, {{ $order->city }} {{ $order->postal_code }}</p></section></div>
<aside class="space-y-4"><section class="rounded-card bg-malam p-5 text-white"><p class="text-xs text-white/60">Status</p><p class="mt-1 font-display text-lg font-bold">{{ str_replace('_', ' ', $order->status) }}</p><p class="mt-4 text-xs text-white/60">Total</p><p class="mt-1 font-display text-xl font-bold">{{ $order->total === null ? 'Belum ditetapkan' : 'Rp'.number_format($order->total, 0, ',', '.') }}</p></section>
@if($order->status === 'waiting_shipping')<form method="post" action="{{ route('admin.shop-orders.shipping', $order) }}" class="rounded-card border border-garis bg-white p-5">@csrf @method('PATCH')<label class="text-sm font-bold text-arang">Ongkos kirim</label><input type="number" name="shipping_cost" min="0" required class="mt-2 w-full rounded-xl border border-garis bg-kertas-isian px-4 py-3"><button class="mt-3 w-full rounded-full bg-daun px-4 py-3 text-sm font-bold text-white">Tetapkan ongkir</button></form>@endif
@if($order->status === 'paid')<form method="post" action="{{ route('admin.shop-orders.process', $order) }}">@csrf @method('PATCH')<button class="w-full rounded-full bg-daun px-4 py-3 text-sm font-bold text-white">Mulai proses</button></form>@endif
@if($order->status === 'processing')<form method="post" action="{{ route('admin.shop-orders.ship', $order) }}" class="space-y-3 rounded-card border border-garis bg-white p-5">@csrf @method('PATCH')<input name="courier" required placeholder="Kurir" class="w-full rounded-xl border border-garis bg-kertas-isian px-4 py-3"><input name="tracking_number" required placeholder="Nomor resi" class="w-full rounded-xl border border-garis bg-kertas-isian px-4 py-3"><button class="w-full rounded-full bg-daun px-4 py-3 text-sm font-bold text-white">Tandai dikirim</button></form>@endif
@if($order->tracking_number)<div class="rounded-card bg-daun-muda p-5 text-sm font-bold text-daun-tua">{{ $order->courier }} · {{ $order->tracking_number }}</div>@endif</aside></div>
@endsection
